# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# ignore all warnings from all dependencies
inhibit_all_warnings!
# ignore warnings from a specific dependency
pod 'FBSDKCoreKit', :inhibit_warnings => true


target 'FridgeManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FridgeManager
    pod 'SwiftLint'
    pod 'Firebase/Firestore'
    pod 'FirebaseFirestoreSwift'
    pod 'Firebase/Analytics'
    pod 'RAMAnimatedTabBarController'
    pod 'RHSideButtons'
 

  target 'FridgeManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FridgeManagerUITests' do
    # Pods for testing
  end

end
